package com.epam.designAndArchitecture.userInterface;

public enum CommandsEnum {
    LOGIN,
    SIGNUP,
    ADD_BOOK,
    DELETE_BOOK,
    ADD_AUTHOR,
    DELETE_AUTHOR,
    SEARCH_BOOKS_BY_PART_AUTHOR_NAME,
    SEARCH_BOOKS_BY_PART_NAME,
    SEARCH_BOOK_BY_ISBN,
    SEARCH_BOOKS_BY_YEAR_RANGE,
    SEARCH_BOOKS_BY_YEAR_PAGES_PART_NAME,
    APPEND_BOOKMARK,
    DELETE_BOOKMARK,
    TAKE_BOOKS_WITH_MY_BOOKMARKS,
    CREATE_NEW_USER,
    BAN_USER,
    TAKE_HISTORY_OPERATIONS,
}
